<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('payments', function (Blueprint $table) {
            $table->id();

            // From Jetpax Last Modified
            // Required
            $table->string('provider_gen_id')->unique();
            $table->string('provider_transaction_id')->nullable();
            $table->string('provider_generated_sign')->nullable();
            $table->integer('amount')->default(0);
            $table->string('type')->nullable();
            $table->morphs('bookable');

            $table->string('provider_gen_url')->nullable();

            $table->string('callback_url')->nullable();
            $table->string('success_url')->nullable();
            $table->string('failure_url')->nullable();

            $table->dateTime('expire_at')->nullable();
            $table->boolean('verified')->default(false);

            //$table->string('status')->default('pending');

            $table->foreignId('payment_provider_id')->constrained('payment_providers')->cascadeOnDelete()->cascadeOnUpdate();

            $table->json('details')->nullable();



            // OLD

//            $table->string('receipt')->unique();
//            $table->string('provider_gen_id')->unique();  // Booking Time Order ID Generated By Razorpay
//            $table->string('provider_ref_id')->nullable();
//            $table->string('provider_gen_sign')->nullable();
//            $table->string('provider_class');
//
//            // Added
//            $table->string('voucher')->nullable();
//            $table->integer('quantity')->default(0);
//            $table->integer('subtotal')->default(0);
//            $table->integer('discount')->default(0);
//            $table->integer('tax')->default(0);
//            $table->integer('total')->default(0);
//
//            $table->json('details')->nullable();
//            $table->json('error')->nullable();
//            $table->boolean('verified')->default(false);
//            $table->string('status')->default('pending');
//            $table->dateTime('expire_at');
//
//            $table->foreignId('order_id')->nullable()->constrained('orders')->cascadeOnUpdate()->nullOnDelete();
//            $table->foreignId('customer_id')->constrained('customers')->cascadeOnDelete()->cascadeOnUpdate();
//            $table->foreignId('payment_provider_id')->nullable()->constrained('payment_providers')->cascadeOnDelete()->cascadeOnUpdate();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
