<?php

namespace App\Helpers\ProductHelper\Support\Types;

use App\Helpers\ProductHelper\Support\AbstractSupportProductSupport;
use App\Models\Attribute\AttributeGroup;
use App\Models\Product\Product;

class Simple extends AbstractSupportProductSupport
{

    /**
     * @param array $data
     * @return bool|Product
     */
    public function create(array $data): bool|Product
    {
        // Create Product
        $product = parent::create($data); // TODO: Change the autogenerated stub

        // Fill Filter Attributes
        $group = AttributeGroup::where(['id' => $product->attribute_group_id])->with('attributes')->first();
        foreach ($group->attributes as $attribute) {
            $data['filter_attributes'][$attribute->code] = null;
        }
        $product->flat()->create([
            'sku' => $data['sku'],
            'filter_attributes' => $data['filter_attributes'],
        ]);

        return $product;
    }

    /**
     * @return bool
     */
    public function isSaleable(): bool
    {
        // TODO: Implement isSaleable() method.
    }

    /**
     * @return int
     */
    public function haveSufficientQuantity(): int
    {
        // TODO: Implement haveSufficientQuantity() method.
    }
}
