<?php

namespace Database\Factories\Product;

use App\Models\Product\Product;
use App\Models\Product\ProductFlat;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Product\Product>
 */
class ProductFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $data = [
            'sku' => $this->faker->unique()->word,
            'type' => Product::SIMPLE,
            'name' => $productName = ucwords($this->faker->unique()->words(2, true)),
            'url' => Str::slug($productName),
            'status' => Product::PUBLISHED,
            'base_price' => $basePrice = fake()->numberBetween(1000, 12000),
            'price' => $basePrice,
            'filter_group_id' => fake()->randomElement([5, 6]),
            'quantity' => 0,
            'is_returnable' => $returnable = fake()->boolean(40),
        ];

        if ($data['is_returnable']) {
            $data = array_merge($data, [
                'return_window' => now()->addDays(rand(1, 4)),
            ]);
        }

        return $data;

    }

    public function configure()
    {
        // Add Product Flat
        $this->afterMaking(function (Product $product) {
            $product->flat()->create(ProductFlat::factory(1)->make());

        });

        return parent::configure(); // TODO: Change the autogenerated stub
    }
}
