<?php

namespace App\Services\ShippingService\Providers\Custom\Support;

class OrderHandler
{
    public static function getOrderDetailArray($id)
    {
        return
            $arrayVar = [
                'data' => [
                    'id' => $id,
                    'channel_id' => random_int(11111, 99999),
                    'channel_name' => 'MANUAL1',
                    'base_channel_code' => 'CS',
                    'is_international' => 0,
                    'is_document' => 0,
                    'channel_order_id' => '1873081902',
                    'customer_name' => 'DemoHome ',
                    'customer_email' => 'abc@gmail.com',
                    'customer_phone' => '9876543236',
                    'customer_address' => '408, Gautami, Kondapur',
                    'customer_address_2' => null,
                    'customer_city' => 'North West Delhi',
                    'customer_state' => 'Delhi',
                    'customer_pincode' => '110088',
                    'customer_country' => 'India',
                    'pickup_code' => '',
                    'pickup_location' => '',
                    'pickup_location_id' => '',
                    'pickup_id' => '',
                    'ship_type' => '',
                    'courier_mode' => '',
                    'currency' => 'INR',
                    'country_code' => 99,
                    'exchange_rate_usd' => 0,
                    'exchange_rate_inr' => 0,
                    'state_code' => 1483,
                    'payment_status' => '',
                    'delivery_code' => '110088',
                    'total' => 345,
                    'total_inr' => 0,
                    'total_usd' => 0,
                    'net_total' => '345.00',
                    'other_charges' => '0.00',
                    'other_discounts' => '0.00',
                    'giftwrap_charges' => '0.00',
                    'expedited' => 0,
                    'sla' => '2 days',
                    'cod' => 0,
                    'tax' => 0,
                    'total_kerala_cess' => '',
                    'discount' => 0,
                    'status' => 'RETURN PENDING',
                    'sub_status' => null,
                    'status_code' => 21,
                    'master_status' => '',
                    'payment_method' => 'prepaid',
                    'purpose_of_shipment' => 0,
                    'channel_created_at' => '21 Sep 2022 05:25 PM',
                    'created_at' => '21 Sep 2022 05:28 PM',
                    'order_date' => '21 Sep 2022',
                    'updated_at' => '21 Sep 2022 05:28 PM',
                    'products' => [
                        [
                            'id' => 365076966,
                            'order_id' => 259492257,
                            'product_id' => 1620533,
                            'name' => 'watch',
                            'sku' => 'Tshirt-Blue-41',
                            'description' => 'WHEAT AND MESLIN DURUM WHEAT : OF SEED QUALITY',
                            'channel_order_product_id' => '365076966',
                            'channel_sku' => 'Tshirt-Blue-41',
                            'hsn' => '',
                            'model' => null,
                            'manufacturer' => null,
                            'brand' => '',
                            'color' => '',
                            'size' => null,
                            'custom_field' => '',
                            'custom_field_value' => '',
                            'custom_field_value_string' => '',
                            'weight' => 0,
                            'dimensions' => '0x0x0',
                            'price' => 345,
                            'cost' => 345,
                            'mrp' => 400,
                            'quantity' => 1,
                            'returnable_quantity' => 0,
                            'tax' => 0,
                            'status' => 1,
                            'net_total' => 345,
                            'discount' => 0,
                            'product_options' => [],
                            'selling_price' => 345,
                            'tax_percentage' => 0,
                            'discount_including_tax' => 0,
                            'channel_category' => 'Default Category',
                            'packaging_material' => '',
                            'additional_material' => '',
                            'is_free_product' => '',
                        ],
                    ],
                    'invoice_no' => '',
                    'shipments' => [
                        'id' => 258878960,
                        'order_id' => 259492257,
                        'order_product_id' => null,
                        'channel_id' => 38026,
                        'code' => '',
                        'cost' => '0.00',
                        'tax' => '0.00',
                        'awb' => null,
                        'rto_awb' => '',
                        'awb_assign_date' => null,
                        'etd' => '',
                        'delivered_date' => '',
                        'quantity' => 1,
                        'cod_charges' => '0.00',
                        'number' => null,
                        'name' => null,
                        'order_item_id' => null,
                        'weight' => 1,
                        'volumetric_weight' => 0.266,
                        'dimensions' => '11.000x11.000x11.000',
                        'comment' => '',
                        'courier' => '',
                        'courier_id' => '',
                        'manifest_id' => '',
                        'manifest_escalate' => false,
                        'status' => 'PENDING',
                        'isd_code' => '+91',
                        'created_at' => '21st Sep 2022 05:28 PM',
                        'updated_at' => '21st Sep 2022 05:28 PM',
                        'pod' => null,
                        'eway_bill_number' => '-',
                        'eway_bill_date' => null,
                        'length' => 11,
                        'breadth' => 11,
                        'height' => 11,
                        'rto_initiated_date' => '',
                        'rto_delivered_date' => '',
                        'shipped_date' => '',
                        'package_images' => '',
                        'is_rto' => false,
                        'eway_required' => false,
                        'invoice_link' => '',
                        'is_darkstore_courier' => 0,
                        'courier_custom_rule' => '',
                        'is_single_shipment' => true,
                    ],
                    'awb_data' => [
                        'awb' => '',
                        'applied_weight' => '',
                        'charged_weight' => '',
                        'billed_weight' => '',
                        'routing_code' => '',
                        'rto_routing_code' => '',
                        'charges' => [
                            'zone' => '',
                            'cod_charges' => '',
                            'applied_weight_amount' => '',
                            'freight_charges' => '',
                            'applied_weight' => '',
                            'charged_weight' => '',
                            'charged_weight_amount' => '',
                            'charged_weight_amount_rto' => '',
                            'applied_weight_amount_rto' => '',
                            'service_type_id' => '',
                        ],
                    ],
                    'order_insurance' => [
                        'insurance_status' => 'No',
                        'policy_no' => 'N/A',
                        'claim_enable' => false,
                    ],
                    'return_pickup_data' => [
                        'id' => 2143757,
                        'name' => 'ashwin ashwin',
                        'email' => 'ashwingunadeep@gmail.com',
                        'address' => 'shiprocket',
                        'address_2' => 'shiprocket',
                        'city' => 'South West Delhi',
                        'state' => 'Delhi',
                        'country' => 'India',
                        'pin_code' => '110030',
                        'phone' => '9562817406',
                        'lat' => null,
                        'long' => null,
                        'order_id' => 259492257,
                        'created_at' => '2022-09-21 17:28:40',
                        'updated_at' => '2022-09-21 17:28:40',
                    ],
                    'company_logo' => null,
                    'allow_return' => 0,
                    'is_return' => 1,
                    'is_incomplete' => 0,
                    'errors' => null,
                    'payment_code' => null,
                    'coupon_is_visible' => false,
                    'coupons' => '',
                    'billing_city' => '',
                    'billing_name' => '',
                    'billing_email' => '',
                    'billing_phone' => '',
                    'billing_alternate_phone' => '',
                    'billing_state_name' => '',
                    'billing_address' => '',
                    'billing_country_name' => '',
                    'billing_pincode' => '',
                    'billing_address_2' => '',
                    'billing_mobile_country_code' => '+91',
                    'isd_code' => '',
                    'billing_state_id' => '',
                    'billing_country_id' => '',
                    'freight_description' => 'Forward charges',
                    'reseller_name' => '',
                    'shipping_is_billing' => 0,
                    'company_name' => 'shiprocket',
                    'shipping_title' => '',
                    'allow_channel_order_sync' => false,
                    'uib-tooltip-text' => 'Re-fetch orders with updated details',
                    'api_order_id' => '',
                    'allow_multiship' => 0,
                    'other_sub_orders' => [],
                    'others' => [
                        'weight' => '1',
                        'quantity' => 1,
                        'buyer_psid' => null,
                        'dimensions' => '11x11x11',
                        'api_order_id' => '',
                        'company_name' => 'shiprocket',
                        'currency_code' => 'INR',
                        'package_count' => '1',
                        'shipping_city' => 'North West Delhi',
                        'shipping_name' => 'DemoHome ',
                        'shipping_email' => 'abc@gmail.com',
                        'shipping_phone' => '9876543236',
                        'shipping_state' => 'Delhi',
                        'custom_order_id' => null,
                        'billing_isd_code' => '+91',
                        'forward_order_id' => null,
                        'shipping_address' => '408, Gautami, Kondapur',
                        'shipping_charges' => '0',
                        'shipping_country' => 'India',
                        'shipping_pincode' => '110088',
                        'shipping_address_2' => '',
                    ],
                    'is_order_verified' => 0,
                    'extra_info' => [
                        'qc_check' => 1,
                        'qc_params' => 'Product Name,Size,Color,Brand,Product Image',
                        'order_type' => 1,
                        'amazon_dg_status' => false,
                        'forward_order_id' => '',
                        'bluedart_dg_status' => false,
                        'other_courier_dg_status' => false,
                        'insurace_opted_at_order_creation' => false,
                    ],
                    'dup' => 0,
                    'is_blackbox_seller' => false,
                    'shipping_method' => 'SR',
                    'refund_detail' => [
                        'refund_mode' => 'Store Credits',
                        'account_holder_name' => '',
                        'account_number' => '',
                        'bank_ifsc' => '',
                        'bank_name' => '',
                    ],
                    'pickup_address' => [],
                    'eway_bill_number' => '',
                    'eway_bill_url' => '',
                    'eway_required' => false,
                    'irn_no' => '',
                    'engage' => null,
                    'seller_can_edit' => false,
                    'seller_can_cancell' => false,
                    'is_post_ship_status' => false,
                    'order_tag' => '',
                    'qc_status' => '',
                    'qc_reason' => '',
                    'qc_image' => '',
                    'product_qc' => [
                        [
                            'product_id' => 365076966,
                            'qc_values' => [
                                'qc_product_name' => [
                                    'value' => 'watch',
                                    'name' => 'Product Name',
                                ],
                                'qc_size' => ['value' => 'asdasd', 'name' => 'Size'],
                                'qc_color' => ['value' => 'asdasd', 'name' => 'Color'],
                                'qc_brand' => ['value' => 'asdas', 'name' => 'Brand'],
                                'qc_product_image' => [
                                    'value' => 'https://s3-ap-southeast-1.amazonaws.com/kr-shipmultichannel/1663238198WTVf4.jpeg',
                                    'name' => 'Product Image',
                                ],
                            ],
                        ],
                    ],
                    'seller_request' => null,
                    'change_payment_mode' => true,
                    'etd_date' => null,
                    'out_for_delivery_date' => null,
                    'delivered_date' => null,
                    'remittance_date' => '',
                    'remittance_utr' => '',
                    'remittance_status' => '',
                    'insurance_excluded' => true,
                    'can_edit_dimension' => true,
                ],
            ];

    }
}
