<?php

namespace App\Filament\Pages;

use Filament\Forms\Components\TextInput;
use Filament\Pages\Page;
use JeffGreco13\FilamentBreezy\Pages\MyProfile as BaseProfile;

class Profile extends BaseProfile
{

    public $current_password;




    public function updateProfile()
    {
        $state = $this->updateProfileForm->getState();
        $verificationNeeded = false;
        if ($state['email'] != $this->user->email)
        {
            $verificationNeeded = true;
        }
        $this->user->update($state);
        if ($verificationNeeded)
        {
            $this->user->sendEmailVerificationNotification();
            $this->notify('success', 'Verification Mail Send Successfully', true);
        }
        $this->notify("success", __('filament-breezy::default.profile.personal_info.notify'));
    }




    protected function getUpdatePasswordFormSchema(): array
    {
        return array_merge([

            TextInput::make('current_password')
                ->label('Current Password')
                ->password()
                ->rules(['required_with:new_password'])
                ->currentPassword()
                ->autocomplete('off')
                ->columnSpan(1),

        ],parent::getUpdatePasswordFormSchema()); // TODO: Change the autogenerated stub
    }


    public function updatePassword()
    {
        parent::updatePassword(); // TODO: Change the autogenerated stub
        $this->reset(["new_password", "new_password_confirmation","current_password"]);
    }



    protected static function shouldRegisterNavigation(): bool
    {
        return false;
    }













}
